[tool.poetry]
name = "picturegatheringPKG"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.10.0"
cryptography = "^39.0.1"
emoji = "^1.7.0"
freezegun = "^1.2.2"
google-api-python-client = "^2.68.0"
lxml = "^4.9.1"
mock = "^4.0.3"
oauthlib = "^3.2.2"
Pillow = "^9.3.0"
PixivPy = "^3.7.0"
plyer = "^2.1.0"
protobuf = "^3.20.2"
pycodestyle = "^2.9.1"
pyppeteer = "^1.0.2"
python = ">=3.9,<4"
requests = "^2.27.1"
requests-html = "^0.10.0"
requests-oauthlib = "^1.3.1"
slackweb = "^1.0.5"
SQLAlchemy = "^1.4.44"
urllib3 = "^1.26.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
