[tool.poetry]
name = "mgPKG"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.11.2"
coverage = "^7.2.1"
coverage-badge = "^1.1.0"
cryptography = "^39.0.1"
emoji = "^1.7.0"
freezegun = "^1.2.2"
google-api-python-client = "^2.78.0"
isort = "^5.12.0"
lxml = "^4.9.2"
mock = "^4.0.3"
oauthlib = "^3.2.2"
Pillow = "^9.4.0"
PixivPy = "^3.7.0"
plyer = "^2.1.0"
protobuf = "^3.20.2"
pycodestyle = "^2.9.1"
pyppeteer = "^1.0.2"
python = ">=3.9,<4"
requests = "^2.28.2"
requests-html = "^0.10.0"
requests-oauthlib = "^1.3.1"
slackweb = "^1.0.5"
SQLAlchemy = "^1.4.46"
urllib3 = "^1.26.14"

[tool.poetry.dev-dependencies]

[tool.isort]
multi_line_output = 9
line_length = 256

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
