[tool.poetry]
name = "mgPKG"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.12.0"
coverage = "^7.2.2"
cryptography = "^39.0.2"
emoji = "^2.2.0"
freezegun = "^1.2.2"
google-api-python-client = "^2.82.0"
isort = "^5.12.0"
mock = "^5.0.1"
oauthlib = "^3.2.2"
pillow = "^9.4.0"
PixivPy = "^3.7.0"
plyer = "^2.1.0"
protobuf = "^3.20.3"
pycodestyle = "^2.10.0"
pyppeteer = "^1.0.2"
python = ">=3.9,<4"
requests = "^2.28.2"
requests-html = "^0.10.0"
requests-oauthlib = "^1.3.1"
slack-sdk = "^3.20.2"
sqlalchemy = "1.4.46"

[tool.poetry.dev-dependencies]

[tool.isort]
line_length = 256
multi_line_output = 9

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
