[tool.poetry]
name = "mgPKG"
version = "2.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.12.0"
coverage = "^7.3.2"
cryptography = "^41.0.5"
emoji = "^2.7.0"
freezegun = "^1.2.2"
google-api-python-client = "^2.108.0"
httpx = "^0.25.1"
isort = "^5.12.0"
mock = "^5.1.0"
pillow = "^10.0.1"
pixivpy3 = "^3.7.4"
plyer = "^2.1.0"
pycodestyle = "^2.11.0"
python = ">=3.11,<4"
requests = "^2.31.0"
slack-sdk = "^3.23.1"
sqlalchemy = "1.4.46"
twitter-api-client = "^0.10.12"

[tool.poetry.dev-dependencies]

[tool.isort]
line_length = 256
multi_line_output = 9

[tool.ruff]
organizeImports = false

[tool.ruff.lint]
ignore = ["F401", "F541", "F841"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
