[tool.poetry]
name = "picturegatheringPKG"
version = "0.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.9,<4"
beautifulsoup4 = "^4.10.0"
cryptography = "^36.0.1"
emoji = "^1.6.3"
freezegun = "^1.1.0"
google-api-python-client = "^2.35.0"
lxml = "^4.9.1"
mock = "^4.0.3"
Pillow = "^9.0.1"
PixivPy = "^3.6.2"
plyer = "^2.0.0"
protobuf = "^3.19.3"
pyppeteer = "^1.0.2"
requests = "^2.27.1"
requests-html = "^0.10.0"
requests-oauthlib = "^1.3.0"
slackweb = "^1.0.5"
SQLAlchemy = "^1.4.29"
urllib3 = "^1.26.8"
pycodestyle = "^2.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
