[tool.poetry]
name = "mgPKG"
version = "2.1.0"
description = ""
authors = ["shift <fantasy_world4423-git@yahoo.co.jp>"]
license = "MIT License"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.12.0"
coverage = "^7.3.0"
cryptography = "^41.0.3"
emoji = "^2.7.0"
freezegun = "^1.2.2"
google-api-python-client = "^2.97.0"
isort = "^5.12.0"
mock = "^5.1.0"
pillow = "^10.0.1"
PixivPy = "^3.7.0"
plyer = "^2.1.0"
protobuf = "^3.20.3"
pycodestyle = "^2.11.0"
pyppeteer = "^1.0.2"
python = ">=3.11,<4"
requests = "^2.31.0"
requests-html = "^0.10.0"
slack-sdk = "^3.21.3"
sqlalchemy = "1.4.46"
twitter-api-client = "^0.10.11"

[tool.poetry.dev-dependencies]

[tool.isort]
line_length = 256
multi_line_output = 9

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
